config/routes.rb
Rails.application.routes.draw do

  resources :transacao_saidas

  resources :transacao_entradas
  get 'mensalidades', to: 'transacao_entradas#mensalidades', as: :mensalidades_transa
  get 'mensalidades/new', to: 'transacao_entradas#mensalidade_new', as: :mensalidades_transa_new
  get 'mensalidades/status', to: 'transacao_entradas#mensalidades_status', as: :mensalidades_transa_status

  resources :socios
  get 'socios/:id/edit_password', to: 'socios#password_change', as: :password_change

  resources :sessions
  get 'home/index'

  root :to => 'sessions#set_roots'
  get "/find_roots" => "sessions#set_roots"
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/socio.rb
class Socio < ActiveRecord::Base
  has_secure_password
  has_many :TransacaoEntrada

  validates_presence_of :cpf , message: 'não pode ficar em branco'
  validates_length_of :cpf, :is => 11, message: 'inválido inserido'
  validates_numericality_of :cpf, message: 'inválido inserido'
  validates_uniqueness_of :cpf, message: 'inválido inserido'
  validates_cpf_format_of :cpf, message: 'inválido inserido'

  validates_presence_of :nome , message: 'não pode ficar em branco'
  validates :nome, length: {in: 5..60, message: 'deve ter entre 5 e 60 caracteres'}

  validates_presence_of :telefone , message: 'não pode ficar em branco'

  validates_presence_of :endereco , message: 'não pode ficar em branco'
  validates :endereco, length: {in: 10..120, message: 'deve ter entre 10 e 120 caracteres'}

  validates_presence_of :cadeira , message: 'não pode ficar em branco'
  validates_uniqueness_of :cadeira , message: 'já existe'
  validates_numericality_of :cadeira, greater_than: 0, message: 'tem que ser positivo'

  validates_presence_of :sexo , message: 'não pode ficar em branco'


  validates_presence_of :permissao, message: 'não pode ficar em branco'

  validates_presence_of :email, message: 'não pode ficar em branco'
  validates :email, :email => true

end

app/controllers/socios_controller.rb
class SociosController < ApplicationController
  before_action :set_socio, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /socios/1/edit_password
  def password_change
    @socio = Socio.find(params[:id])
  end

  # GET /socios
  # GET /socios.json
  def index
    @socios = Socio.all.reject {|socio| socio.id == 1}
  end
  # GET /socios/1
  # GET /socios/1.json
  def show
  end

  # GET /socios/new
  def new
    @socio = Socio.new
  end

  # GET /socios/1/edit
  def edit
  end

  # POST /socios
  # POST /socios.json
  def create
    @socio = Socio.new(socio_params)

    respond_to do |format|
      if @socio.save
        format.html { redirect_to @socio, notice: 'Socio criado com sucesso.' }
        format.json { render :show, status: :created, location: @socio }
      else
        format.html { render :new }
        format.json { render json: @socio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /socios/1
  # PATCH/PUT /socios/1.json
  def update
    respond_to do |format|
      if @socio.update(socio_params)
        format.html { redirect_to @socio, notice: 'Socio modificado com sucesso.' }
        format.json { render :show, status: :ok, location: @socio }
      else
        format.html { render :edit }
        format.json { render json: @socio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /socios/1
  # DELETE /socios/1.json
  def destroy
    @socio.destroy
    respond_to do |format|
      format.html { redirect_to socios_url, notice: 'Socio removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_socio
      @socio = Socio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def socio_params
      params.require(:socio).permit(:nome, :cpf, :email, :telefone, :endereco, :dataNascimento, :sexo, :cadeira, :password, :password_confirmation, :permissao, :created_at, :updated_at)
    end
end

app/helpers/socios_helper.rb
module SociosHelper
end

app/views/socios/_form.html.erb
<%= form_for(@socio) do |f| %>
  <% if @socio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@socio.errors.count, "erro") %> encontrados:</h2>

      <ul>
      <% @socio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento%><br>
    <%= f.date_select :dataNascimento, start_year: 1900 , class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.select :sexo, ['Masculino', 'Feminino', 'Outro'], class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :cadeira %><br>
    <%= f.number_field :cadeira, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.password_field :password , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :"confirmação senha"%><br>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :permissão %><br>
    <%= f.text_field :permissao , class: "form-control"%>
    <%#= f.select :permissao, options_for_select(['Socio','Diretor','Tesoureiro'], :selected => params[:permissao]), {}, { :class => 'span3 controls controls-row' } %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary', value: 'Concluir' %>
  </div>
<% end %>

app/views/socios/_formEdit.html.erb
<%= form_for(@socio) do |f| %>
  <% if @socio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@socio.errors.count, "erro") %> econtrados:</h2>

      <ul>
      <% @socio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :data_de_nascimento%><br>
    <%= f.date_select :dataNascimento, start_year: 1900  %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.select :sexo, ['Masculino', 'Feminino', 'Outro']%>
  </div>
  <div class="field">
    <%= f.label :cadeira %><br>
    <%= f.number_field :cadeira %>
  </div>
  <div class="field">
    <%= f.label :permissão %><br>
    <%= f.text_field :permissao %>
    <%#= f.select :permissao, options_for_select(['Socio','Diretor','Tesoureiro'], :selected => params[:permissao]), {}, { :class => 'span3 controls controls-row' } %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary', value: 'Concluir'%> |
    <%= link_to 'Detalhe', @socio, class: 'btn btn-primary'%> |
    <%= link_to 'Voltar', socios_path, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/socios/_formPassword.html.erb
<%= form_for(@socio) do |f| %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control", :disabled => true %>
    <%= f.label "Este é seu Email?" %><br>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.password_field :password , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :"confirmação senha"%><br>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary', value: 'Concluir'%> |
    <%= link_to 'Voltar', mensalidades_transa_path, class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/socios/edit.html.erb
<h1>Edição de Sócio</h1>

<%= render 'formEdit' %>

app/views/socios/index.html.erb
  <h1>
    Sócios cadastrados
  </h1>


<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nome:</th>
      <th>Cpf:</th>
      <th>Email:</th>
      <th>Telefone:</th>
      <th>Endereco:</th>
      <th>Nascimento:</th>
      <th>Sexo:</th>
      <th>Cadeira:</th>
      <%#<th>Senha:</th>%>
      <th>Permissão:</th>
      <th>Criado_em:</th>
      <th>Modificado_em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @socios.each do |socio| %>
      <tr>
        <td><%= socio.nome %></td>
        <td><%= socio.cpf %></td>
        <td><%= socio.email %></td>
        <td><%= socio.telefone %></td>
        <td><%= socio.endereco %></td>
        <td><%= socio.dataNascimento %></td>
        <td><%= socio.sexo %></td>
        <td><%= socio.cadeira %></td>
        <td><%= socio.permissao %></td>
        <td><div><%= socio.created_at %></div></td>
        <td><%= socio.updated_at %></td>
        <td><%= link_to 'Exibir', socio %></td>
        <td><%= link_to 'Editar', edit_socio_path(socio) %></td>
        <td><%= link_to 'Deletar', socio, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<form action="/socios/new" class="buttonHolder">
    <input type="submit" class="btn btn-primary" value="Cadastrar novo sócio" />
</form>

app/views/socios/new.html.erb
<h1>Alteração de Senha</h1>

<%= render 'form' %>

<%= link_to 'Voltar', "mensalidades" %>

app/views/socios/password_change.html.erb
<h1>Trocar Senha</h1>

<%= render 'formPassword' %>

app/views/socios/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @socio.nome %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @socio.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @socio.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @socio.telefone %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @socio.endereco %>
</p>

<p>
  <strong>Data Nasc.:</strong>
  <%= @socio.dataNascimento %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @socio.sexo %>
</p>

<p>
  <strong>Cadeira:</strong>
  <%= @socio.cadeira %>
</p>

<p>
  <strong>Permissao:</strong>
  <%= @socio.permissao %>
</p>

<p>
  <strong>Criado em:</strong>
  <%= @socio.created_at %>
</p>

<p>
  <strong>Modificado em:</strong>
  <%= @socio.updated_at %>
</p>

<%= link_to 'Editar', edit_socio_path(@socio), class: 'btn btn-primary'%> |
<%= link_to 'Voltar', socios_path, class: 'btn btn-primary'%>