config/routes.rb
Rails.application.routes.draw do

  resources :transacao_saidas

  resources :transacao_entradas
  get 'mensalidades', to: 'transacao_entradas#mensalidades', as: :mensalidades_transa
  get 'mensalidades/new', to: 'transacao_entradas#mensalidade_new', as: :mensalidades_transa_new
  get 'mensalidades/status', to: 'transacao_entradas#mensalidades_status', as: :mensalidades_transa_status

  resources :socios
  get 'socios/:id/edit_password', to: 'socios#password_change', as: :password_change

  resources :sessions
  get 'home/index'

  root :to => 'sessions#set_roots'
  get "/find_roots" => "sessions#set_roots"
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/transacao_saida.rb
class TransacaoSaida < ActiveRecord::Base
  has_attached_file :img_comprov, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :img_comprov, content_type: /\Aimage\/.*\z/

  validates_presence_of :valor , message: 'não pode ficar em branco'
  validates_presence_of :data_saida , message: 'não pode ficar em branco'
  validates_presence_of :justifica_saida , message: 'não pode ficar em branco'
  validates_numericality_of :valor, greater_than: 0, message: 'inválido inserido'
end

app/controllers/transacao_saidas_controller.rb
class TransacaoSaidasController < ApplicationController
  before_action :set_transacao_saida, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /transacao_saidas
  # GET /transacao_saidas.json
  def index
    @transacao_saidas = TransacaoSaida.all
  end

  # GET /transacao_saidas/1
  # GET /transacao_saidas/1.json
  def show
  end

  # GET /transacao_saidas/new
  def new
    @transacao_saida = TransacaoSaida.new
  end

  # GET /transacao_saidas/1/edit
  def edit
  end

  # POST /transacao_saidas
  # POST /transacao_saidas.json
  def create
    @transacao_saida = TransacaoSaida.new(transacao_saida_params)

    respond_to do |format|
      if @transacao_saida.save
        format.html { redirect_to @transacao_saida, notice: 'Transação de saida criada com sucesso.' }
        format.json { render :show, status: :created, location: @transacao_saida }
      else
        format.html { render :new }
        format.json { render json: @transacao_saida.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transacao_saidas/1
  # PATCH/PUT /transacao_saidas/1.json
  def update
    respond_to do |format|
      if @transacao_saida.update(transacao_saida_params)
        format.html { redirect_to @transacao_saida, notice: 'Transação de saida modificada com sucesso.' }
        format.json { render :show, status: :ok, location: @transacao_saida }
      else
        format.html { render :edit }
        format.json { render json: @transacao_saida.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transacao_saidas/1
  # DELETE /transacao_saidas/1.json
  def destroy
    @transacao_saida.destroy
    respond_to do |format|
      format.html { redirect_to transacao_saidas_url, notice: 'Transacao de saida deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transacao_saida
      @transacao_saida = TransacaoSaida.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transacao_saida_params
      params.require(:transacao_saida).permit(:valor, :data_saida, :justifica_saida, :img_comprov, :created_at, :updated_at)
    end
end

app/helpers/transacao_saidas_helper.rb
module TransacaoSaidasHelper
end

app/views/transacao_saidas/_form.html.erb
<%= form_for(@transacao_saida) do |f| %>
  <% if @transacao_saida.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transacao_saida.errors.count, "erro") %> encontrados:</h2>

      <ul>
      <% @transacao_saida.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :data_de_saida %><br>
    <%= f.date_select :data_saida , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :justificativa_de_saida %><br>
    <%= f.text_area :justifica_saida, size: "20x6", class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :imagem_do_comprovante %><br>
    <%= f.file_field :img_comprov , class: "form-control"%>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary', value: 'Concluir' %>
  </div>
<% end %>

app/views/transacao_saidas/edit.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li class="active"><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<%= render 'form' %>

<%= link_to 'Exibir', @transacao_saida %> |
<%= link_to 'Voltar', transacao_saidas_path %>

app/views/transacao_saidas/index.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li class="active"><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Id:</th>
      <th>Valor:</th>
      <th>Data:</th>
      <th>Justificativa:</th>
      <th>Comprovante:</th>
      <th>Criado_em:</th>
      <th>Modificado_em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transacao_saidas.each do |transacao_saida| %>
      <tr>
        <td><%= transacao_saida.id %></td>
        <td><%= transacao_saida.valor %></td>
        <td><%= transacao_saida.data_saida %></td>
        <td><%= transacao_saida.justifica_saida %></td>
        <td>
          <%= image_tag transacao_saida.img_comprov.url(:thumb)%>
          <%= link_to "Exibir", transacao_saida.img_comprov.url(:original, false) %>
        </td>
        <td><%= transacao_saida.created_at %></td>
        <td><%= transacao_saida.updated_at %></td>
        <td><%= link_to 'Exibir', transacao_saida %></td>
        <td><%= link_to 'Editar', edit_transacao_saida_path(transacao_saida) %></td>
        <td><%= link_to 'Deletar', transacao_saida, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transacao_saidas/new.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li class="active"><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<%= render 'form' %>

<%#= link_to 'Back', transacao_saidas_path %>

app/views/transacao_saidas/show.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li  class="active"><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<p>
  <strong>ID:</strong>
  <%= @transacao_saida.id%>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transacao_saida.valor %>
</p>

<p>
  <strong>Data:</strong>
  <%= @transacao_saida.data_saida %>
</p>

<p>
  <strong>Justificativa:</strong>
  <%= @transacao_saida.justifica_saida %>
</p>

<p>
  <strong>Comprovante:</strong>
  <%= image_tag @transacao_saida.img_comprov.url(:thumb)%>
  <%= link_to "Exibir", @transacao_saida.img_comprov.url(:original, false) %>
</p>

<p>
  <strong>Criado em:</strong>
  <%= @transacao_saida.created_at %>
</p>

<p>
  <strong>Modificado em:</strong>
  <%= @transacao_saida.updated_at %>
</p>

<%= link_to 'Editar', edit_transacao_saida_path(@transacao_saida) %> |
<%= link_to 'Voltar', transacao_saidas_path %>