config/routes.rb
Rails.application.routes.draw do

  resources :transacao_saidas

  resources :transacao_entradas
  get 'mensalidades', to: 'transacao_entradas#mensalidades', as: :mensalidades_transa
  get 'mensalidades/new', to: 'transacao_entradas#mensalidade_new', as: :mensalidades_transa_new
  get 'mensalidades/status', to: 'transacao_entradas#mensalidades_status', as: :mensalidades_transa_status

  resources :socios
  get 'socios/:id/edit_password', to: 'socios#password_change', as: :password_change

  resources :sessions
  get 'home/index'

  root :to => 'sessions#set_roots'
  get "/find_roots" => "sessions#set_roots"
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/transacao_entrada.rb
class TransacaoEntrada < ActiveRecord::Base
belongs_to :socios

validates_presence_of :valor , message: 'não pode ficar em branco'
validates_presence_of :data_entrada , message: 'não pode ficar em branco'
validates_presence_of :justifica_entrada , message: 'não pode ficar em branco'
validates_numericality_of :valor, greater_than: 0, message: 'inválido inserido'

def self.search(search)
  if search
    @transacao_entradas = TransacaoEntrada.where(idSocio: "#{search}", tipo: "Mensalidade").all
  else
    @transacao_entradas = TransacaoEntrada.where(tipo: "Mensalidade").all
  end
end

end

app/controllers/transacao_entradas_controller.rb
class TransacaoEntradasController < ApplicationController
  before_action :set_transacao_entrada, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /transacao_entradas
  # GET /transacao_entradas.json
  def index
    @transacao_entradas = TransacaoEntrada.all
    if params[:search]
      @transacao_entradas = TransacaoEntrada.search(params[:search])
    else
      @transacao_entradas = TransacaoEntrada.all
    end
  end


  # GET /transacao_entradas/1
  # GET /transacao_entradas/1.json
  def show
  end

  # GET /transacao_entradas/new
  def new
    @socios = Socio.all
    @transacao_entrada = TransacaoEntrada.new
  end

  # GET /mensalidades
  def mensalidades
    @socios = Socio.all
    @transacao_entrada = TransacaoEntrada.where(tipo: "Mensalidade").all
  end

  # GET /mensalidades/new
  def mensalidade_new
    @socios = Socio.all
    @transacao_entrada = TransacaoEntrada.new
  end

  # GET /mensalidades/status
  def mensalidades_status
    @socios = Socio.all
    @transacao_entrada = TransacaoEntrada.where(tipo: "Mensalidade").all
  end

  # GET /mensalidades/1/edit
  def edit
  end

  # POST /transacao_entradas
  # POST /transacao_entradas.json
  def create
    @transacao_entrada = TransacaoEntrada.new(transacao_entrada_params)

    puts "DEBUG: #{params[:transacao_entrada][:idSocio]}"

    respond_to do |format|
      if @transacao_entrada.save
        format.html { redirect_to @transacao_entrada, notice: 'Transacao de entrada criada com sucesso.' }
        format.json { render :show, status: :created, location: @transacao_entrada }
      else
        format.html { render :new }
        format.json { render json: @transacao_entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transacao_entradas/1
  # PATCH/PUT /transacao_entradas/1.json
  def update
    respond_to do |format|
      if @transacao_entrada.update(transacao_entrada_params)
        format.html { redirect_to @transacao_entrada, notice: 'Transacao de entrada modifacada com sucesso.' }
        format.json { render :show, status: :ok, location: @transacao_entrada }
      else
        format.html { render :edit }
        format.json { render json: @transacao_entrada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transacao_entradas/1
  # DELETE /transacao_entradas/1.json
  def destroy
    @transacao_entrada.destroy
    respond_to do |format|
      format.html { redirect_to transacao_entradas_url, notice: 'Transacao entrada deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transacao_entrada
      @transacao_entrada = TransacaoEntrada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transacao_entrada_params
      params.require(:transacao_entrada).permit(:valor, :data_entrada, :justifica_entrada, :tipo, :idSocio, :created_at, :updated_at)
    end
end

app/helpers/transacao_entradas_helper.rb
module TransacaoEntradasHelper
	private
    # Use callbacks to share common setup or constraints between actions.
    def set_transacao_entrada
      @socio = Socio.find(params[:id])
    end
end

app/views/transacao_entradas/_form.html.erb
<%= form_for(@transacao_entrada) do |f| %>
  <% if @transacao_entrada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transacao_entrada.errors.count, "erro") %> encontrados:</h2>

      <ul>
      <% @transacao_entrada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor, class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :data_entrada %><br>
    <%= f.date_select :data_entrada %>
  </div>
  <div class="field">
    <%= f.label :justificativa_de_entrada %><br>
    <%= f.text_area :justifica_entrada, size: "20x6" , class: "form-control"%>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.select :tipo, ['Mensalidade','Doação', 'Outro']%>
  </div>
    <div class="field">
      <%= f.label :Socios %><br>
      <%= f.collection_select :idSocio, Socio.all.reject {|socio| socio.id == 1}, :id, :nome%>
    </div>

  <div class="actions">
    <%= f.submit class: 'btn btn-primary', value: 'Concluir' %>
  </div>
<% end %>

app/views/transacao_entradas/edit.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li class="active"><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<%= render 'form' %>

<%= link_to 'Exibir', @transacao_entrada %> |
<%= link_to 'Voltar', transacao_entradas_path %>

app/views/transacao_entradas/index.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li class="active"><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>ID:</th>
      <th>Valor:</th>
      <th>Data:</th>
      <th>Justificativa:</th>
      <th>Tipo:</th>
      <th>Criado_em:</th>
      <th>Modificado_em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transacao_entradas.each do |transacao_entrada| %>
      <tr>
        <td><%= transacao_entrada.id %></td>
        <td><%= transacao_entrada.valor %></td>
        <td><%= transacao_entrada.data_entrada %></td>
        <td><%= transacao_entrada.justifica_entrada %></td>
        <td><%= transacao_entrada.tipo %></td>
        <td><%= transacao_entrada.created_at %></td>
        <td><%= transacao_entrada.updated_at %></td>
        <td><%= link_to 'Exibir', transacao_entrada%></td>
        <td><%= link_to 'Editar', edit_transacao_entrada_path(transacao_entrada) %></td>
        <td><%= link_to 'Deletar', transacao_entrada, method: :delete, data: { confirm: 'Você tem Certeza' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transacao_entradas/mensalidade_new.html.erb
<ul class="nav nav-tabs">
  <li><a href="/mensalidades/status">Situação dos Sócios</a></li>
  <li><a href="/mensalidades">Mensalidades</a></li>
  <li class="active"><a href="/mensalidades/new">Lançar Nova Mensalidade</a></li>
</ul><br>


<%= render 'form' %>

<%#= link_to 'Back', transacao_entradas_path %>

app/views/transacao_entradas/mensalidades.html.erb
<ul class="nav nav-tabs">
  <li><a href="/mensalidades/status">Situação dos Sócios</a></li>
  <li class="active"><a href="/mensalidades">Mensalidades</a></li>
  <li><a href="/mensalidades/new">Lançar Nova Mensalidade</a></li>
</ul><br>

<table class="table table-condensed">
  <div class="row">
    <%= form_tag mensalidades_transa_path, :method => 'get', class: 'input-group'  do %>
    <div class="col-lg-4">
      <div class="input-group">
        <span class="input-group-btn">
          <%= submit_tag "Filtrar!", class: "btn btn-default", :search => nil%>
        </span>
        <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Digite o ID do Sócio...' %>
      </div><!-- /input-group -->
    </div><!-- /.col-lg-4 -->
    <% end %>
  </div><!-- /.row --><br>

  <thead>
    <tr>
      <th>ID:</th>
      <th>Socio:</th>
      <th>Valor:</th>
      <th>Data:</th>
      <th>Tipo:</th>
      <th>Criado_em:</th>
      <th>Modificado_em:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% TransacaoEntrada.search(params[:search]).each do |transacao_entrada| %>
      <tr>
        <td><%= transacao_entrada.id %></td>
        <td><%= transacao_entrada.idSocio %></td>
        <td><%= transacao_entrada.valor %></td>
        <td><%= transacao_entrada.data_entrada %></td>
        <td><%= transacao_entrada.tipo %></td>
        <td><%= transacao_entrada.created_at %></td>
        <td><%= transacao_entrada.updated_at %></td>
        <td><%#= link_to 'Exibir', transacao_entrada%></td>
        <td><%#= link_to 'Editar', edit_transacao_entrada_path(transacao_entrada) %></td>
        <td><%#= link_to 'Deletar', transacao_entrada, method: :delete, data: { confirm: 'Você tem Certeza' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transacao_entradas/mensalidades_status.html.erb
<ul class="nav nav-tabs">
  <li  class="active"><a href="/mensalidades/status">Situação dos Sócios</a></li>
  <li><a href="/mensalidades">Mensalidades</a></li>
  <li><a href="/mensalidades/new">Lançar Nova Mensalidade</a></li>
</ul><br>

<div class="col-md-4">
  <h3>Mês: <%=Date.current.mon%> / Ano: <%=Date.current.year%></h3>

  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Socio:</th>
        <th>Situação:</th>
      </tr>
    </thead>

    <tbody>
      <% @socios.reject {|socio| socio.id == 1}.each do |socio| %>
        <tr>
          <td><%= socio.nome %></td>
          <%-if @transacao_entrada.exists?(['idSocio = ?', "#{socio.id}"])%>
            <%@transacao_entrada.where(["idSocio = ?", socio.id]).each do |status|%>
              <% if status.data_entrada.mon < Date.current.mon%>
                <td  bgcolor="#ff6666">NÃO PAGO</td>
              <% else %>
                <td  bgcolor="#4d94ff">PAGO</td>
              <% end %>
            <%end%>
          <%else%>
           <td bgcolor="#ff6666">NÃO PAGO</td>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transacao_entradas/new.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<%= render 'form' %>

<%#= link_to 'Back', transacao_entradas_path %>

app/views/transacao_entradas/show.html.erb
<ul class="nav nav-tabs">
  <li><a href="/transacao_entradas/new">Nova Transação Entrada</a></li>
  <li class="active"><a href="/transacao_entradas">Exibir Transações de Entrada</a></li>
  <li><a href="/transacao_saidas/new">Nova Transação Saida</a></li>
  <li><a href="/transacao_saidas">Exibir Transações de Saida</a></li>
</ul><br>

<p>
  <strong>Id entrada:</strong>
  <%= @transacao_entrada.id %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @transacao_entrada.valor %>
</p>

<p>
  <strong>Data entrada:</strong>
  <%= @transacao_entrada.data_entrada %>
</p>

<p>
  <strong>Justifica entrada:</strong>
  <%= @transacao_entrada.justifica_entrada %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @transacao_entrada.tipo %>
</p>

<p>
  <strong>Criado em:</strong>
  <%= @transacao_entrada.created_at %>
</p>

<p>
  <strong>Modificado em:</strong>
  <%= @transacao_entrada.updated_at %>
</p>

<%= link_to 'Editar', edit_transacao_entrada_path(@transacao_entrada) %> |
<%= link_to 'Voltar', transacao_entradas_path %>